### ISSUE TITLE
Arduino found, but data can't be received

### ISSUE THREAD

**Issue by GreyDevSergal** [OmarAflak/Arduino-USB#1]
No errors can be found, am I missing something?
Arduino is found, but data does not seem to be received/sent

```java
@Override
    protected void onStart() {
        super.onStart();
        arduino.setArduinoListener(this);
        display("Start");
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        arduino.unsetArduinoListener();
        arduino.close();
    }

    @Override
    public void onArduinoAttached(UsbDevice device) {
        String init = "init";

        display("Arduino found...");
        arduino.open(device);
        arduino.send(init.getBytes());
    }

    @Override
    public void onArduinoDetached() {
        display("Arduino lost...");
    }

    @Override
    public void onArduinoMessage(byte[] bytes) {
        display(new String(bytes));
    }
```

**Comment by omaraflak** [comment]
There is a missing listener in your code - **onArduinoOpened** -. You have to wait for it to send messages. Make sure you're using the latest version of the library : 

**[https://github.com/OmarAflak/Arduino-Library](https://github.com/OmarAflak/Arduino-Library)**

You have a simple example in the readme.

Also, this repo is just an app demo code and this issue is not related to the app so I'm closing it. If you're still having problems, please open an issue on the [library repo](https://github.com/OmarAflak/Arduino-Library/issues).
